### ISSUE TITLE
Document handling of numbers as column names

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#16]
Document type datasets that have columns named after numbers see those column names transformed

From slack:

`AFAICT this was a previously known issue, fixed about a year ago, but I can only assume the affected datasets were not migrated. Anyways, we didn't support support columns named as numbers, like you have on that dataset. Once support for that was added, column names like '6' were automatically converted to 'col_6' and are now supported. As I mentioned old datasets were not migrated, so I don't think you can query that dataset as-is unless it's reuploaded.`

**Comment by simaob** [comment]
@santostiago what's the status of this documentation?

**Comment by santostiago** [comment]
https://github.com/resource-watch/doc-api/pull/26
