### ISSUE TITLE
Question: could we have a Docker recipe?

### ISSUE THREAD

**Issue by edwardpmorris** [resource-watch/doc-api#160]
I am not familiar with Ruby (and I am lazy), setting up the specific Ruby version in Unix to be able to check edits for the unnamed style of markdown used here, is well, a bit annoying. Maybe to aid contributors in checking the HTML output we could supply a docker recipe?

**Comment by tiagojsag** [comment]
I understand the convenience but that's just another dependency to configure and maintain on the project in exchange for little gain. IMO rvm and bundler are pretty easy to configure.

**Comment by tiagojsag** [comment]
@edwardpmorris I just noticed this repo already has a Dockerfile, so with a bit of googling you should be able to get this up and running, if you still prefer that.
