### ISSUE TITLE
Document endpoint to access a list of all registered MSs

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#18]
# get list of MSs
From Slack:
hey, what’s the endpoint that lists all the registered microservices?
http://staging-api.globalforestwatch.org/api/v1/microservice

You should also add that you need to have the admin role to access this

# delete MSs
from slack: 
there's a DELETE endpoint you can use

https://github.com/control-tower/control-tower/blob/develop/app/src/routes/api/v1/microservice.router.js#L68
app/src/routes/api/v1/microservice.router.js:68
```router.delete('/:id', Utils.isLogged, Utils.isAdmin, MicroserviceRouter.delete);```
control-tower/control-towerAdded by GitHub
keep in mind that this does not actually delete the microservice, it schedules it for being delete. There's a cron task that does the actual deleting, so the process is async. @sergio.gordillo or @ra can you add more details as to why this happens this way, please?

**Comment by simaob** [comment]
Hi @santostiago don't forget to document this, please!

**Comment by santostiago** [comment]
https://github.com/resource-watch/doc-api/pull/25
