### ISSUE TITLE
Update docs on dataset listing sorting criteria

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#31]
https://vizzuality.slack.com/archives/C2LKQ3NDU/p1551861015019600

https://github.com/resource-watch/dataset/blob/040633d5efcf53d6af96389d260a99d532570f5d/app/test/e2e/dataset-search.spec.js

**Comment by agnlez** [comment]
PR: https://github.com/resource-watch/doc-api/pull/32
