### ISSUE TITLE
Document 'env' update on resources

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#35]
# Dataset:
- Updating env on a dataset is possible
- It propagates that env change to all associated layers and widgets

# Layer
- It's not possible to update the env of a layer on it's own
- You can create a layer with a different env that the one of the associated dataset. If no env is provided, "production" is used

# Widget
- You can update the env of an individual widget
- You can create a widget with a different env that the one of the associated dataset. If no env is provided, "production" is used

**Comment by 01painadam** [comment]
see https://github.com/resource-watch/doc-api/pull/50
