### ISSUE TITLE
Permissions for widget/user

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#36]
1- who can delete a widget?
- Users with MANAGER who are in the same `app` as the widget and are in the widget's `userId`
- Users with ADMIN role, who are in the same `app` as the widget

2- can an user with role USER edit a widget not created by them?
- no, only ADMINs can edit widgets belonging to other users

3- which type of users can be created by which user ROLE?
- registration is open to everyone, which results in a user with role USER
- using the POST method, MANAGERS can create USER or MANAGERS, ADMIN can create any role

**Comment by santostiago** [comment]
Maybe it would be worth having a permissions section of the documentation.
But for now I'll add this to each endpoint. I'll leave the issue open to be discussed.

**Comment by santostiago** [comment]
https://github.com/resource-watch/doc-api/pull/44
