### ISSUE TITLE
what happens to the widgets/layers of a dataset when we remove them? Can we delete datasets with widgets/layers?

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#37]
when a dataset is deleted, the following delete operations are issued:
- knowledge_graph
- layer
- widget
- metadata
- vocabulary

more info: https://github.com/resource-watch/dataset/blob/5d4b6d1a3b243f5ba985b444633c0f6acf78b35d/app/test/e2e/dataset-delete.spec.js#L46

**Comment by santostiago** [comment]
https://github.com/resource-watch/doc-api/pull/46
