### ISSUE TITLE
document that GET layer filters by env=production implicitly

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#56]
same as https://github.com/resource-watch/doc-api/issues/27 but for layers

Also document that requests like http://api.resourcewatch.org/dataset/c5fe87d6-49ca-4c68-ad7e-ea48145562e0/?includes=layer do NOT filter by env

**Comment by pablopareja** [comment]
Done! 
Here you have the PR https://github.com/resource-watch/doc-api/pull/60
