### ISSUE TITLE
Document `resouce watch manager`s `contact-us` endpoint

### ISSUE THREAD

**Issue by tiagojsag** [resource-watch/doc-api#63]
`curl -X POST \
  http://staging-api.globalforestwatch.org/contact-us \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: <add token here>' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 405' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: staging-api.globalforestwatch.org' \
  -H 'Postman-Token: 3f4c9c13-9821-4742-a1f9-663aa73a8b19,d90e6d37-ca1c-4f19-9176-760df0a794ef' \
  -H 'Referer: http://staging-api.globalforestwatch.org/contact-us' \
  -H 'User-Agent: PostmanRuntime/7.17.1' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F email=foo@vizzuality.com \
  -F 'text=sample text' \
  -F topic=topicTest`

**Comment by pablopareja** [comment]
Please check the following PR https://github.com/resource-watch/doc-api/pull/64
